name: env_e15190
channels:
   - anaconda
   - conda-forge
dependencies:
   - python=3.8
   - conda-build

   # common scientific tools
   - numpy>=1.19.0
   - numba>=0.51.0
   - astropy>=4.0
   - scipy>=1.6

   # data structure and files I/O
   - pytables>=3.6.1
   - tabulate>=0.8.9
   - pandas>=1.1.0
   - pymysql>=1.0.1
   - uproot>=4.0.7
   - root=6.22.6
   - mako>=1.1.4

   # statistical tools and machine learning
   - scikit-learn>=0.24.0

   # plotting
   - matplotlib>=3.3.0

   # miscellaneous
   - cryptography=3.4.7
   - lxml>=4.6.3
   - autopep8
